language: java
sudo: false
jdk:
   - openjdk8
   - openjdk11
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/a5eb23de882eeafa54e6
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
  - secure: sCV/wozedYbj3vJlaH/Yqgy2bmz3fBSEyf7aL6BOyldmdknN0VSDyW9mYH9Adl9eiOtAgUpYjIW/ygOrhfqKaqr7wvjIXhSUpc1bG499mzW21qOJcwVIAOsS/Zc9NWUuoJb8BPjP2b5l/TPg8mTk644QiHT9dOu2U3iB0kj72Gk=
  - secure: XOvPUZpq4oObLwLA/1pfR4oUiq1pdqMfyhJh04trwQuA7n2O2wJScNYbmUYufs/46XBWj67wxrf0OjpccL5PHhBvtYWBIgvtJbLLE7WIgwhTsgp4XIJAPMOXQFc24MLd5wKPs+EIQeCWpa0jrSlbasell8uzqHsfxyn/jZoqOu8=
  - secure: jxWh5gGxPFQ7LpKvAoQCVnvS+8TldqFCENIz3s93rPa4zMJVHqIPoY98hHfdc9bQYscheaRxRoOplmFheq4ulrU6KPPFND5zAO5bKj427EGIolIo47XBqEMV8iQjJrdCWdiS44/1bdjiTml/OmotUIllt7dxaBvRVLfO6O3CpO4=
  - secure: DglYE2jfpuvTLBhhD+pZd+FqE3SmAHRWl+qerCWLqPQUPT0GzyzB3nET13208f7AesSGu/pPGaIKRmeO5dkyo4joC1q3lM3Kh5vy64OWll81pBA/JmwhpVK3hoZtRRmuzyn3czLlwpUOjK+I5iPdYxOjVSCp5cGHk3kFUJQg5jw=
  - secure: q31v3Thw70HqvvCbgPJnKr+HoQ2rSmwR4Y9J6aXbGcXhyNJsQAFDjstwR6A9nn6UqKNHKDpefx4zH9K/uwRLYoi8k2kg4EnXsiMQ4/9wqkV9IinxUQRbRoljiwRR10z1NMJfWwJq6TaAImMzDIgZtRhiJYTksBRV1YIoYhpS5Xw=
  - secure: T5eiIHkbrwZdh6FpAK1MqeyhL9dVDDqa0YtlF/tDnUcL0HgK/3HD9N4Bsth9xCYcSNU4oPp/nZYVFGE7ZnEj6u+KXXiIIyzQVzmQbvCXC8c5QVFz9EVQXwgr1QoaMWgOPr5ctiYBWoSj9nmbu+g4TKeO1lBp+f3wpye31dN2kJg=
